import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'
import './globals.css'
import './page.css'
import Image from 'next/image'

const dm_sans = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
  weight: ["300", "400", "500"],
  style: ["italic", "normal"],
  variable: "--font-dmsans"
})

export const metadata: Metadata = {
  title: 'Process',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={dm_sans.className}>
          <Image className='logo' width={120} height={100} alt='logo' src='/Layer_2.svg' />
        <section className='containerApp'>
          {children}
        </section>
      </body>
    </html>
  )
}